help_message_file: "assets/help_message.md"
session_file: "session.txt"

delete_session_file_on_start: true
use_add_command: true # whether to use the add command to add items to the poll or adding every captured message to the poll
prefix: "!" # the prefix used to trigger commands
default_quantity_number: 1 # the default quantity number used when adding items to the poll

paying_feature: # allows users to react to the poll summary message after it has been closed. Paid users react with an emoji, while unpaid users receive after x time a reminder to pay.
  enabled: true # whether to enable the paying feature
  emoji: "ğŸ’¸" # the emoji which needs to be used to confirm payment to closed poll summary message
  auto_send_emoji: true # whether to automatically react to poll summary message with the emoji
  reminder_delay: "1h" # The time after which unpaid users will be reminded to pay.  Use a duration like "30m", "1h", "24h", "7d".

reactions:
  enabled: true # whether to enable reactions
  types:
    error:
      enabled: true # whether to enable the error reaction
      emoji: "âŒ"
    success:
      enabled: true # whether to enable the success reaction
      emoji: "âœ…"
    removed:
      enabled: true # whether to enable the removed reaction
      emoji: "ğŸ—‘"

# all available commands
commands: # the command name needs to be the same as the python file command name
  help_command: ["help", "h"] # a list of trigger names for the command
  create_poll_command: ["create", "poll", "lunchy"]
  remove_item_command: ["remove"]
  list_items_command: ["list", "ls", "status"]
  close_poll_command: ["close", "finish"]
  add_item_command: ["add", "a"]
  release_notes_command: ["release", "releasenotes"]
  reopen_poll_command: ["reopen"]
